language: cpp

os: linux

compiler: gcc

# build instructions
script:
   - cmake -DENABLE_TRAVIS=ON CMakeLists.txt
   - make

#只有指定的分支提交时才会运行脚本
branches:
  only:
    - main
    
notifications:
  email: true
 
